// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextilSwagger.Models;

#nullable disable

namespace TextilSwagger.Migrations.EntradasInventarioDb
{
    [DbContext(typeof(EntradasInventarioDbContext))]
    [Migration("20241003042305_EntradasInventario")]
    partial class EntradasInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TextilSwagger.Models.EntradasInventario", b =>
                {
                    b.Property<int>("almacenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("almacenid"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("entradaid")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaentrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("productoid")
                        .HasColumnType("int");

                    b.Property<int>("proveedorid")
                        .HasColumnType("int");

                    b.HasKey("almacenid");

                    b.ToTable("EntradasInventario");
                });
#pragma warning restore 612, 618
        }
    }
}
