// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextilSwagger.Models;

#nullable disable

namespace TextilSwagger.Migrations.SalidaInventarioDb
{
    [DbContext(typeof(SalidaInventarioDbContext))]
    partial class SalidaInventarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TextilSwagger.Models.SalidaInventario", b =>
                {
                    b.Property<int>("salidaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("salidaid"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("empleadoid")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechasalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("productoid")
                        .HasColumnType("int");

                    b.HasKey("salidaid");

                    b.ToTable("SalidaInventario");
                });
#pragma warning restore 612, 618
        }
    }
}
