//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Sistem_Textil.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioTextil")]
    public interface ServicioTextil {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/validarusuarioempleado", ReplyAction="http://tempuri.org/ServicioTextil/validarusuarioempleadoResponse")]
        bool validarusuarioempleado(string nombre, string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/validarusuarioempleado", ReplyAction="http://tempuri.org/ServicioTextil/validarusuarioempleadoResponse")]
        System.Threading.Tasks.Task<bool> validarusuarioempleadoAsync(string nombre, string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/ValidacionProveedor", ReplyAction="http://tempuri.org/ServicioTextil/ValidacionProveedorResponse")]
        string ValidacionProveedor(int proveedorid, string nombre, string contacto, string telefono, string email, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/ValidacionProveedor", ReplyAction="http://tempuri.org/ServicioTextil/ValidacionProveedorResponse")]
        System.Threading.Tasks.Task<string> ValidacionProveedorAsync(int proveedorid, string nombre, string contacto, string telefono, string email, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/EstadoPedidoCompra", ReplyAction="http://tempuri.org/ServicioTextil/EstadoPedidoCompraResponse")]
        string EstadoPedidoCompra(string nombre, string contacto, string estado, string fecha, int cantidad, int productoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/EstadoPedidoCompra", ReplyAction="http://tempuri.org/ServicioTextil/EstadoPedidoCompraResponse")]
        System.Threading.Tasks.Task<string> EstadoPedidoCompraAsync(string nombre, string contacto, string estado, string fecha, int cantidad, int productoid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/detallepedido", ReplyAction="http://tempuri.org/ServicioTextil/detallepedidoResponse")]
        string detallepedido(int pedidoid, int productoid, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/detallepedido", ReplyAction="http://tempuri.org/ServicioTextil/detallepedidoResponse")]
        System.Threading.Tasks.Task<string> detallepedidoAsync(int pedidoid, int productoid, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/entradainventario", ReplyAction="http://tempuri.org/ServicioTextil/entradainventarioResponse")]
        string entradainventario(string fechaentrega, int productoid, int cantidad, int proveedorid, int almacenid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/entradainventario", ReplyAction="http://tempuri.org/ServicioTextil/entradainventarioResponse")]
        System.Threading.Tasks.Task<string> entradainventarioAsync(string fechaentrega, int productoid, int cantidad, int proveedorid, int almacenid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/almacen", ReplyAction="http://tempuri.org/ServicioTextil/almacenResponse")]
        string almacen(string ubicacion, string referencia, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/almacen", ReplyAction="http://tempuri.org/ServicioTextil/almacenResponse")]
        System.Threading.Tasks.Task<string> almacenAsync(string ubicacion, string referencia, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Productos", ReplyAction="http://tempuri.org/ServicioTextil/ProductosResponse")]
        string Productos(string nombre, string descripcion, string categoria, int stock, string ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Productos", ReplyAction="http://tempuri.org/ServicioTextil/ProductosResponse")]
        System.Threading.Tasks.Task<string> ProductosAsync(string nombre, string descripcion, string categoria, int stock, string ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/salidainventario", ReplyAction="http://tempuri.org/ServicioTextil/salidainventarioResponse")]
        string salidainventario(string feche_salida, int empleadoid, int productoid, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/salidainventario", ReplyAction="http://tempuri.org/ServicioTextil/salidainventarioResponse")]
        System.Threading.Tasks.Task<string> salidainventarioAsync(string feche_salida, int empleadoid, int productoid, int stock);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Empleado", ReplyAction="http://tempuri.org/ServicioTextil/EmpleadoResponse")]
        string Empleado(string nombre, string apellido, string dni, string rango, string fecha, string email, string sueldo, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Empleado", ReplyAction="http://tempuri.org/ServicioTextil/EmpleadoResponse")]
        System.Threading.Tasks.Task<string> EmpleadoAsync(string nombre, string apellido, string dni, string rango, string fecha, string email, string sueldo, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Clientes", ReplyAction="http://tempuri.org/ServicioTextil/ClientesResponse")]
        string Clientes(string nombre, string apellido, string dni, string fecha, string telefono, string ruc, string email, string ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Clientes", ReplyAction="http://tempuri.org/ServicioTextil/ClientesResponse")]
        System.Threading.Tasks.Task<string> ClientesAsync(string nombre, string apellido, string dni, string fecha, string telefono, string ruc, string email, string ubicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/DetallesPedidoCliente", ReplyAction="http://tempuri.org/ServicioTextil/DetallesPedidoClienteResponse")]
        string DetallesPedidoCliente(string productoid, string cantidad, string clienteid, string fechapedido, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/DetallesPedidoCliente", ReplyAction="http://tempuri.org/ServicioTextil/DetallesPedidoClienteResponse")]
        System.Threading.Tasks.Task<string> DetallesPedidoClienteAsync(string productoid, string cantidad, string clienteid, string fechapedido, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Entregas", ReplyAction="http://tempuri.org/ServicioTextil/EntregasResponse")]
        string Entregas(string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/Entregas", ReplyAction="http://tempuri.org/ServicioTextil/EntregasResponse")]
        System.Threading.Tasks.Task<string> EntregasAsync(string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/detallemany_entrega", ReplyAction="http://tempuri.org/ServicioTextil/detallemany_entregaResponse")]
        string detallemany_entrega(string productoid, string cantidad, string fechapedido, string estado, string pedidomany, string entreid, string fechaentrega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ServicioTextil/detallemany_entrega", ReplyAction="http://tempuri.org/ServicioTextil/detallemany_entregaResponse")]
        System.Threading.Tasks.Task<string> detallemany_entregaAsync(string productoid, string cantidad, string fechapedido, string estado, string pedidomany, string entreid, string fechaentrega);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioTextilChannel : Proyecto_Sistem_Textil.ServiceReference1.ServicioTextil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTextilClient : System.ServiceModel.ClientBase<Proyecto_Sistem_Textil.ServiceReference1.ServicioTextil>, Proyecto_Sistem_Textil.ServiceReference1.ServicioTextil {
        
        public ServicioTextilClient() {
        }
        
        public ServicioTextilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTextilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTextilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTextilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool validarusuarioempleado(string nombre, string dni) {
            return base.Channel.validarusuarioempleado(nombre, dni);
        }
        
        public System.Threading.Tasks.Task<bool> validarusuarioempleadoAsync(string nombre, string dni) {
            return base.Channel.validarusuarioempleadoAsync(nombre, dni);
        }
        
        public string ValidacionProveedor(int proveedorid, string nombre, string contacto, string telefono, string email, string direccion) {
            return base.Channel.ValidacionProveedor(proveedorid, nombre, contacto, telefono, email, direccion);
        }
        
        public System.Threading.Tasks.Task<string> ValidacionProveedorAsync(int proveedorid, string nombre, string contacto, string telefono, string email, string direccion) {
            return base.Channel.ValidacionProveedorAsync(proveedorid, nombre, contacto, telefono, email, direccion);
        }
        
        public string EstadoPedidoCompra(string nombre, string contacto, string estado, string fecha, int cantidad, int productoid) {
            return base.Channel.EstadoPedidoCompra(nombre, contacto, estado, fecha, cantidad, productoid);
        }
        
        public System.Threading.Tasks.Task<string> EstadoPedidoCompraAsync(string nombre, string contacto, string estado, string fecha, int cantidad, int productoid) {
            return base.Channel.EstadoPedidoCompraAsync(nombre, contacto, estado, fecha, cantidad, productoid);
        }
        
        public string detallepedido(int pedidoid, int productoid, int cantidad) {
            return base.Channel.detallepedido(pedidoid, productoid, cantidad);
        }
        
        public System.Threading.Tasks.Task<string> detallepedidoAsync(int pedidoid, int productoid, int cantidad) {
            return base.Channel.detallepedidoAsync(pedidoid, productoid, cantidad);
        }
        
        public string entradainventario(string fechaentrega, int productoid, int cantidad, int proveedorid, int almacenid) {
            return base.Channel.entradainventario(fechaentrega, productoid, cantidad, proveedorid, almacenid);
        }
        
        public System.Threading.Tasks.Task<string> entradainventarioAsync(string fechaentrega, int productoid, int cantidad, int proveedorid, int almacenid) {
            return base.Channel.entradainventarioAsync(fechaentrega, productoid, cantidad, proveedorid, almacenid);
        }
        
        public string almacen(string ubicacion, string referencia, int cantidad) {
            return base.Channel.almacen(ubicacion, referencia, cantidad);
        }
        
        public System.Threading.Tasks.Task<string> almacenAsync(string ubicacion, string referencia, int cantidad) {
            return base.Channel.almacenAsync(ubicacion, referencia, cantidad);
        }
        
        public string Productos(string nombre, string descripcion, string categoria, int stock, string ubicacion) {
            return base.Channel.Productos(nombre, descripcion, categoria, stock, ubicacion);
        }
        
        public System.Threading.Tasks.Task<string> ProductosAsync(string nombre, string descripcion, string categoria, int stock, string ubicacion) {
            return base.Channel.ProductosAsync(nombre, descripcion, categoria, stock, ubicacion);
        }
        
        public string salidainventario(string feche_salida, int empleadoid, int productoid, int stock) {
            return base.Channel.salidainventario(feche_salida, empleadoid, productoid, stock);
        }
        
        public System.Threading.Tasks.Task<string> salidainventarioAsync(string feche_salida, int empleadoid, int productoid, int stock) {
            return base.Channel.salidainventarioAsync(feche_salida, empleadoid, productoid, stock);
        }
        
        public string Empleado(string nombre, string apellido, string dni, string rango, string fecha, string email, string sueldo, string telefono) {
            return base.Channel.Empleado(nombre, apellido, dni, rango, fecha, email, sueldo, telefono);
        }
        
        public System.Threading.Tasks.Task<string> EmpleadoAsync(string nombre, string apellido, string dni, string rango, string fecha, string email, string sueldo, string telefono) {
            return base.Channel.EmpleadoAsync(nombre, apellido, dni, rango, fecha, email, sueldo, telefono);
        }
        
        public string Clientes(string nombre, string apellido, string dni, string fecha, string telefono, string ruc, string email, string ubicacion) {
            return base.Channel.Clientes(nombre, apellido, dni, fecha, telefono, ruc, email, ubicacion);
        }
        
        public System.Threading.Tasks.Task<string> ClientesAsync(string nombre, string apellido, string dni, string fecha, string telefono, string ruc, string email, string ubicacion) {
            return base.Channel.ClientesAsync(nombre, apellido, dni, fecha, telefono, ruc, email, ubicacion);
        }
        
        public string DetallesPedidoCliente(string productoid, string cantidad, string clienteid, string fechapedido, string estado) {
            return base.Channel.DetallesPedidoCliente(productoid, cantidad, clienteid, fechapedido, estado);
        }
        
        public System.Threading.Tasks.Task<string> DetallesPedidoClienteAsync(string productoid, string cantidad, string clienteid, string fechapedido, string estado) {
            return base.Channel.DetallesPedidoClienteAsync(productoid, cantidad, clienteid, fechapedido, estado);
        }
        
        public string Entregas(string fecha) {
            return base.Channel.Entregas(fecha);
        }
        
        public System.Threading.Tasks.Task<string> EntregasAsync(string fecha) {
            return base.Channel.EntregasAsync(fecha);
        }
        
        public string detallemany_entrega(string productoid, string cantidad, string fechapedido, string estado, string pedidomany, string entreid, string fechaentrega) {
            return base.Channel.detallemany_entrega(productoid, cantidad, fechapedido, estado, pedidomany, entreid, fechaentrega);
        }
        
        public System.Threading.Tasks.Task<string> detallemany_entregaAsync(string productoid, string cantidad, string fechapedido, string estado, string pedidomany, string entreid, string fechaentrega) {
            return base.Channel.detallemany_entregaAsync(productoid, cantidad, fechapedido, estado, pedidomany, entreid, fechaentrega);
        }
    }
}
